- name: provisioning
  hosts: all
  become: yes

  tasks:
    - name: yum update
      yum: 
        name: '*'
        state: latest

    - name: install requires
      yum:
        name: 
          - gcc
          - git
<<<<<<< HEAD
=======
          - docker
          - python-pip
>>>>>>> 025f85042dbc794f0009918725e7eb7b2a306498
          - python-devel
          - openssl-devel
          - libselinux-python
        state: latest

    - name: install molecule
      pip: 
        name: 
          - molecule
<<<<<<< HEAD
        state: latest
=======
          - docker-py
>>>>>>> 025f85042dbc794f0009918725e7eb7b2a306498
