- name: provisioning
  hosts: all
  become: yes

  tasks:
    - name: yum update
      yum: 
        name: '*'
        state: latest

    - name: install requires
      yum:
        name: 
          - gcc
          - git
          - python-devel
          - openssl-devel
          - libselinux-python
        state: latest

    - name: install molecule
      pip: 
        name: 
          - molecule
