- name: provisioning
  hosts: all
  become: yes

  tasks:
    - name: yum update
      yum: 
        name: '*'
        state: latest

    - name: install requires
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - gcc
          - git
          - docker
          - python-pip
          - python-devel
          - openssl-devel
          - libselinux-python
    - name: install molecule
      pip: 
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - pip
          - molecule
          - docker-py
